#!/bin/bash
#below scripts assume you are using cloudera quick start vm

sqoop import \
--connect jdbc:mysql://quickstart.cloudera/retail_db \
--username retail_dba
--password cloudera
--table order_items
--targrt-dir /user/cloudera/retail/order_items

