#!/bin/bash
flume-ng version

# create conf folder
mkdir -p /home/cloudera/flume/conf

########################### Netcat to Logger ###########################
# create conf for netcat-mem-logger
cd /home/cloudera/flume/conf
vi example.conf

# flume cmd
flume-ng agent -name a1 \
--conf /home/cloudera/flume/conf \
--conf-file /home/cloudera/flume/conf/example.conf

# telnet to logger
telnet localhost 44444

###########################  Netcat to HDFS  ###########################
# create conf for netcat-mem-hdfs
cd /home/cloudera/flume/conf
vi hdfs-simple.conf

# delete hdfs folder if it exists
hdfs dfs -rm -R /user/cloudera/flume
hdfs dfs -ls /user/cloudera

# flume cmd
flume-ng agent -name a1 \
--conf /home/cloudera/flume/conf \
--conf-file /home/cloudera/flume/conf/hdfs-simple.conf

# telnet to hdfs
telnet localhost 44444

# check the file in hdfs - for every 2min the temp file will be rolled out if there is any event in that time frame
hdfs dfs -ls /user/cloudera/flume


